flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/martin-kolinek/some-board-game-rules.git
    commit: d38d7c6a247d432c02be8e483f93e2be29247db1
extra-deps:
- reflex-0.4.0
- reflex-dom-0.3
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- clay-0.11
resolver: lts-6.19
