flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/martin-kolinek/some-board-game-rules.git
    commit: 2a2bbb8f23f05ba9eeec819f73a3a8b3733662bc
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 63cb8f83deb68f416ba95afe3d1c5372a40dca43
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: e636a3a7a34529116e91c1b1dda567701f1daa18
  extra-dep: true
  subdirs:
  - reflex-dom-core
  - reflex-dom
- location:
    git: https://github.com/afcady/dependent-sum-template
    commit: 68fc1a90580ea8f20775491cf651eefea422212a
  extra-dep: true

extra-deps:
- clay-0.12.1
- ghcjs-dom-0.8.0.0
- jsaddle-0.8.3.2
- jsaddle-webkit2gtk-0.8.3.1
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- ghcjs-dom-jsaddle-0.8.0.0
- gi-webkit2-4.0.12
- webkit2gtk3-javascriptcore-0.14.2.1
- jsaddle-dom-0.8.0.0
- gi-javascriptcore-4.0.12

resolver: lts-8.11
