flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/martin-kolinek/some-board-game-rules.git
    commit: 2a2bbb8f23f05ba9eeec819f73a3a8b3733662bc
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 3a4cb7966016c36a197a33bf9b394ec21dfe30e5
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: f3b310145a1afa6b448bdb060141ec16c18f0342
  extra-dep: true
  subdirs:
  - reflex-dom-core
  - reflex-dom
- location:
    git: https://github.com/afcady/dependent-sum-template
    commit: 68fc1a90580ea8f20775491cf651eefea422212a
  extra-dep: true

extra-deps:
- clay-0.12.1
- ghcjs-dom-0.9.2.0
- jsaddle-0.9.3.0
- jsaddle-webkit2gtk-0.9.0.0
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- ghcjs-dom-jsaddle-0.9.2.0
- gi-webkit2-4.0.12
- webkit2gtk3-javascriptcore-0.14.2.1
- jsaddle-dom-0.9.2.0
- gi-javascriptcore-4.0.12

resolver: lts-8.11
