flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/martin-kolinek/some-board-game-rules.git
    commit: cd4a42a5562b08e420c9e6cee7091db0218bb3f7
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex
    commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom
    commit: 2b52a41341489d967b71fe82292a61ad77bfe226
  extra-dep: true

extra-deps:
- clay-0.12.1
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1

resolver: lts-6.30
